package com.banyuan.cn.Outer.exceptiondemo;

import java.util.Scanner;

public class ExceptionDemo {

    /**
     * 什么叫异常? java程序在运行过程中,或者是说在编译过程中出现的错误
     *
     */

    public static void main(String[] args) {
//        Scanner  sc=new Scanner(System.in);
//        System.out.println("请输入一个数据:");
//        int  num1=sc.nextInt();
//        System.out.println("请输入一个数据:");
//        int  num2=sc.nextInt();
//
//        System.out.println("和是:"+(num1+num2));

        //   java.util.InputMismatchException

        int [] arr=new  int[5];
     //   System.out.println(arr[4]);
    // java.lang.ArrayIndexOutOfBoundsException: 5
       // System.out.println(arr[5]);
        // arr=null; //java.lang.NullPointerException

       // System.out.println(arr[0]);

        //java.lang.ArithmeticException: / by zero
     //   System.out.println(1/0); //当程序遇到异常的时候会导致整个程序终止

//        for (int i = 0; i < 100; i++) {
//            System.out.println("--"+i);
//        }

        //  stackOverflowException

//        while(true){
//            System.out.println("我是你爸爸...");
//        }

//        show("你好");
//
//        show("你好");
//
//        show("你好");
//
//        show("你好");

    }





}
